### PR TITLE
Changes to CI configuration to use Ubuntu 20.04

### PR DESCRIPTION
**Pull request by joachimmetz**

### CODE REVIEW

**Comment by joachimmetz** [comment]
This is failing because dfImageTools pip install pulls in more recent pre-release of dfVFS. Changes to install dfImageTools from the GIFT PPA https://github.com/google/turbinia/pull/985

**Comment by joachimmetz** [comment]
@hacktobeer Hold off with merging this one for now, need to get a more recent version of dfimagetools into GIFT PPA stable first

**Comment by joachimmetz** [comment]
@aarontp PR is ready for review

**Comment by joachimmetz** [comment]
@aarontp if you want stable to pass, we'll have to wait until the next plaso release

**Comment by aarontp** [comment]
I think the changes to the `file_system_timeline.py` have been updated in https://github.com/google/turbinia/pull/1051/files .  Should we remove the changes to that file from this PR and keep just the changes to `actions.yaml` (and update the description as appropriate)?

**Comment by joachimmetz** [comment]
would need to take a look when time permits

**Comment by joachimmetz** [comment]
@aarontp removed the changes to file_system_timeline would need to take a look of them if the issue in https://github.com/google/turbinia/issues/983 has been addressed

**Comment by aarontp** [comment]
Sounds good.  I'll merge this as is, and then we can check separately to confirm whether #983 is fixed.  Thanks!

**Review by aarontp — APPROVED** [review]
LGTM

**Pull request merged**
