### PR TITLE
Don't use fsstat to determine partition filesystem

### PR DESCRIPTION
**Pull request by dfjxs**
Using dfVFS to determine partition filesystem rather than fsstat, since fsstat doesn't support XFS

### CODE REVIEW

**Comment by aarontp** [comment]
I think it's probably fine as a minimum.  Another option would be to keep the fsstat task, but only run it on partitions with filesystem that are supported by fsstat.  That way we can still get the detailed output from fsstat for most common cases.

**Comment by dfjxs** [comment]
SGTM. Ready for review.

**Comment by joachimmetz** [comment]
Maybe also consider running fsstat for both type gpt and mbr (see: https://github.com/sleuthkit/sleuthkit/issues/1444)

alternatively consider `fdisk -l image.raw` or `gdisk -l image.raw`

**Review by aarontp — APPROVED** [review]
LGTM!

**Pull request merged**
