### PR TITLE
Tox setup

### PR DESCRIPTION
**Pull request by alimez**
Setup tox for turbinia documentation.

### CODE REVIEW

**Comment by alimez** [comment]
@aarontp We can't set this up to run with travis. We have a different setup for that than [dftimewolf](https://github.com/log2timeline/dftimewolf/blob/7816e0315a2f7a37adfe340187476acd3c0e043f/.travis.yml) or [plaso](https://github.com/log2timeline/plaso/blob/a8bd797d253c8f0d79f0d17e493afae164d8e16f/config/travis/runtests.sh). We might need to change that in the future.

**Comment by alimez** [comment]
For some reason travis results aren't showing under the review section but here it is: https://travis-ci.org/github/google/turbinia/builds/728490204

**Comment by alimez** [comment]
Looked into different ways to run doc tests in travis only when the docs directory is changed. Apparently, there are no easy ways around this and there's a feature request for it https://github.com/travis-ci/travis-ci/issues/6301 that's been open for 4 years. And also this https://travis-ci.community/t/how-to-skip-jobs-based-on-the-files-changed-in-a-subdirectory/2979/13 around the same problem.

@aarontp ptal.

**Review by aarontp — APPROVED** [review]
LGTM

**Pull request merged**
