### PR TITLE
Turbinia install docs update

### PR DESCRIPTION
**Pull request by wajihyassine**
### Description of the change

Replace outdated install docs with updated ones

### Checklist

- [ X] All tests were successful.
- [ X] Documentation updated.

### CODE REVIEW

**Comment by wajihyassine** [comment]
@jleaniz if you can please review if anything missing with new API setup

@hacktobeer if you wouldn't mind testing on your end when you have a chance

@aarontp for high level look

**Comment by hacktobeer** [comment]
Will do the following. 

- [x] check docker install stack
- [ ] check kubernetes (minikube) install

**Review by aarontp — APPROVED** [review]
LGTM from a high level!

**Review by hacktobeer — APPROVED** [review]
LGTM, docker and minikube tested/

**Pull request merged**
