### PR TITLE
[DRAFT] Added l2tdevtools configuration and added tests that use GIFT PPA

### PR DESCRIPTION
**Pull request by joachimmetz**
* Added l2tdevtools project and dependencies configuration
* Added tests that use GIFT PPA

### CODE REVIEW

**Comment by joachimmetz** [comment]
@aarontp FYI this PR is still WIP, I did not see Travis being invoked initially when I created a github draft PR, hence I made this a full PR.

**Comment by aarontp** [comment]
Thanks @joachimmetz .   LMK when this is ready for review then.

Regarding labels: Do you have a suggestion for what labels to have for the project?  I see Plaso has a lot of them, but I'm not sure how many are actually used.  For now I added "WIP" and "blocked" labels and applied the former to this PR.

**Comment by joachimmetz** [comment]
@aarontp for plaso a lot of the labels have been introduced when we had a need for them. Which labels work best for Turbinia is up to you, a wip label works for me.

**Comment by jleaniz** [comment]
@joachimmetz @aarontp is this obsolete now? if so, should we close it out?

**Comment by joachimmetz** [comment]
let's close it for now, if needed reopen

**Pull request closed without merging**
