### PR TITLE
Update turbinia-api-client and turbinia-client

### LINKED ISSUE #1354: [Bug]: Error in turbinia-client result task
### What steps will reproduce the bug?

* Install from HEAD
* `$ turbinia-client result task <TaskID>`

### What is the expected behavior?

Get results/output from task

### What do you see instead?

```
$ turbinia-client result task 2a6eda8baeb74a5787e7fc58f244a934
2023-10-04 15:25:15,766 INFO turbinia - Using configuration instance name -> default with host http://localhost:8000
Traceback (most recent call last):
  File "/home/aaronpeterson/src/turbinia/turbinia/api/cli/turbinia_client/core/commands.py", line 88, in get_task_result
    api_response = api_instance.get_task_output(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/home/aaronpeterson/src/turbinia/turbinia/api/client/turbinia_api_lib/api/turbinia_request_results_api.py", line 211, in get_task_output
    raise ValueError("Error! Please call the get_task_output_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data")
ValueError: Error! Please call the get_task_output_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/bin/turbinia-client", line 33, in <module>
    sys.exit(load_entry_point('turbinia-client', 'console_scripts', 'turbinia-client')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/bin/turbinia-client", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aaronpeterson/src/turbinia/turbinia/api/cli/turbinia_client/turbiniacli_tool.py", line 109, in <module>
    main()
  File "/home/aaronpeterson/src/turbinia/turbinia/api/cli/turbinia_client/turbiniacli_tool.py", line 102, in main
    cli.main()
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia-talks/env/turbinia-client/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaronpeterson/src/turbinia/turbinia/api/cli/turbinia_client/core/commands.py", line 104, in get_task_result
    log.error(f'Error reading saved results file {filename}: {exception}')
                                                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'filename' where it is not associated with a value
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jleaniz**
### Description of the change

This PR updates ```turbinia-api-lib``` and ```turbinia-client```

The Python API library was generated using ```openapi-generator``` (latest release v7.0.1). The requirements in this version align with fastapi < 0.99.0 because newer versions produce OpenAPI 3.1 specs which the generator does not yet fully support. For this reason, I am locking fastapi to <0.99.0 temporarily to be consistent with the requirements in ```turbinia-api-lib``` for ```pydantic``` and ```urllib3```

Once support for OpenAPI 3.1 is fully implemented in the ```openapi-generator```, we can loosen the FastAPI version.

Additionally, we should not be using urrlib3[secure] extra because it'll be deprecated (see https://github.com/urllib3/urllib3/issues/2680) -- so i adjusted the requirement.

### Applicable issues

- fixes #1354 

### Additional information

* The ApiResponse object exposes downloaded data in a ```raw_data``` attribute. The ```read_chunks``` method is no longer available to the client.
* Small change to the way the cli tool calls the ```upload_evidence``` method. The API library now handles file reading for the client, so we just pass a list of file paths instead.

### Checklist

- [X] All tests were successful.
- [X] Unit tests added.
- [X] Documentation updated.

### CODE REVIEW

**Review by aarontp — APPROVED** [review]
LGTM

**Comment by aarontp** [comment]
New changes, LGTM too

**Comment by spacether** [comment]
@jleaniz if you want openapi v3.1.0 support, have you considered using [openapi-json-schema-generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator)?
- It is where the python client generator that you use is continuing its development
- Openapi v3.1.0 support was added in [v3.1.0 of openapi-json-schema-generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/3.1.0) and is tested using the json schema test suite

**Comment by jleaniz** [comment]
@spacether thanks for pointing that out. I wasn't aware of openapi-json-schema-generator, I'll check it out. Is the python generator from ```openapi-generator``` no longer going to be supported? Hopefully the APi methods we're calling from the generated client won't change too much.

**Comment by spacether** [comment]
`openapi-generator` has a different python generator that was created by William, the main maintainer of that project. It uses pyantic v2.
- it does not ensure that all json schema validations are run like the old python generator / openapi-json-schema-generator does
- in my opinion openapi-generator is not taking steps to support openapi v3.1.0. I was the main one pushing feature additions there. No one else was contributing on them. When I met with the core team about it, the message that I received was that building out those features was not something that they cared about in Sept 2022. [The issue tracking 3.1.0 in their project is here](https://github.com/OpenAPITools/openapi-generator/issues/9083) Since then, I have not seen any progress posed in that issue or in [their 3.1.0 project](https://github.com/orgs/OpenAPITools/projects/4/views/1)

**Pull request merged**
