### PR TITLE
Fixes optional configuration variables

### PR DESCRIPTION
**Pull request by lincoln1233**
Responding to Issue #101, "Clean up config."  

-Adds and sets previously unincluded optional configuration variables to a null string. 

-Not sure about removal of INSTANCE, DEVICE_NAME, SCRATCH_PATH.

### CODE REVIEW

**Comment by aarontp** [comment]
Sorry for the late review, I was out on vacation.

Thanks for the PR.  I think we actually want to remove these from config/__init__.py rather than adding them back into the config though.  I thought they had been removed already, but I guess I just haven't noticed since I must still have them set in my configs.

Let me know if you want to do that, or I can do it in a separate PR.  Thanks!

**Comment by lincoln1233** [comment]
hey, whatever you think is best. I just made the PR to keep the current install working as it currently. your call, but do you foresee Turbinia leveraging Timesketch?

**Comment by aarontp** [comment]
Yeah we'll definitely integrate with Timesketch. I actually spoke with
Johan (Timesketch lead) before the break about the best way to do the
integration, and hope to have something within a few weeks.  The
implementation probably won't use a static username/password in this way
though, so let's remove it altogether for now (that was actually the
intention in #81), and we can add back the appropriate config vars when
they're needed.

**Comment by lincoln1233** [comment]
awesome sounds good

**Comment by aarontp** [comment]
FYI, given the discussion above, I'm going to close this PR.

**Pull request closed without merging**
