### PR TITLE
Remove hashes.json check

### PR DESCRIPTION
**Pull request by rgayon**
See https://github.com/google/turbinia/issues/629#issuecomment-731263422

### CODE REVIEW

**Comment by hacktobeer** [comment]
This would not generate a hashes.json for *all* files that are extract by image_exporter, correct? Not just the one for the ssh config files.

**Comment by hacktobeer** [comment]
e2e test failed. Is the --no-hashes switch something added in a recent plaso release? if so, from which release is this supported?

https://github.com/google/turbinia/pull/828/checks?check_run_id=2775389325#step:9:594

**Comment by rgayon** [comment]
> e2e test failed. Is the --no-hashes switch something added in a recent plaso release? if so, from which release is this supported?
> 
> https://github.com/google/turbinia/pull/828/checks?check_run_id=2775389325#step:9:594

plaso release 20210412 has the flag

**Comment by rgayon** [comment]
> This would not generate a hashes.json for _all_ files that are extract by image_exporter, correct? Not just the one for the ssh config files.

I believe in all cases turbinia runs image_export.py, we don't want that file to be generated. It is not something we're actually "extracting" and it can then be confused as an evidence for following tasks

**Comment by hacktobeer** [comment]
Thanks for the last commit, removing that apt update fixes the e2e tests. I'll have a look tomorrow and merge.

**Review by hacktobeer — APPROVED** [review]

**Pull request merged**
