### PR TITLE
Fixed EWF support

### PR DESCRIPTION
**Pull request by Slaynot**
### Description of the change

- Added back ewfmount command in worker docker
- Added tests for EWF support. Test data was taken from https://github.com/log2timeline/dfvfs/tree/main/test_data as advised in #1116

### Applicable issues

- #1437
- #1116

### Additional information

The bug was introduced in the worker Dockerfile in 3450b2d.

### Checklist

- [ x] All tests were successful.
- [ x] Unit tests added.

### CODE REVIEW

**Comment by jleaniz** [comment]
Hi @Slaynot - thanks for the contribution. Could you please sign the CLA for us to be able to merge these changes?

**Comment by Slaynot** [comment]
I did, the check seems to not work as the email associated with the commits is not the same as the one used to sign the CLA. Not too sure what I can do about that.

**Comment by jleaniz** [comment]
@aarontp do you know how to fix the CLA issue without having to reopen the PR?

**Comment by aarontp** [comment]
I'm not sure if we can retrigger this with another email address, but I'll look into that.

**Comment by jleaniz** [comment]
@Slaynot if you want to expedite this being merged, it's probably best to reopen the PR and make sure all commits use the same user/email you signed the CLA with.

**Pull request closed without merging**
