### PR TITLE
Add test coverage to test run script.

### LINKED ISSUE #1405: Test coverage no longer showing by default
### What is the feature you are proposing?

Test coverage numbers used to be in the default test output, but aren't showing up anymore for some reason.  It would be nice to add this back so that we can see what coverage is like easily.

### What would this feature improve or what problem would it solve?

Visibility into test coverage.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by hacktobeer**
### Description of the change
Add test coverage to test run script (run_tests.py)

### Applicable issues
- fixes #1405 

### Checklist

- [ ] All tests were successful.

### CODE REVIEW

**Comment by hacktobeer** [comment]
@jleaniz There seems to be a dependency issue with the unit test image build? Any ideas?
https://github.com/google/turbinia/actions/runs/7167242287/job/19512947605?pr=1406#step:4:2929

**Comment by hacktobeer** [comment]
I think I fixed it:
- updated libbde-python (which pulled in a couple of other updated packages)
- locked poetry lock file
- updated yara test as new rules generate 4 detections instead of 3

@jleaniz PTAL if I did the poetry stuff right....

**Comment by hacktobeer** [comment]
Test coverage output - https://github.com/google/turbinia/actions/runs/7183560134/job/19562612102?pr=1406#step:7:2011

**Review by wajihyassine — APPROVED** [review]
LGTM thanks for fixing the broken tests the poetry updates look right to me

**Comment by wajihyassine** [comment]
I also chatted with @aarontp and said it was fine to merge to fix the tests since @jleaniz will be out for some time

**Pull request merged**
